apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blackbeard.fullname" . }}-ui
  labels:
    {{- include "blackbeard.labels" . | nindent 4 }}
    {{- include "blackbeard.selectorLabels" (dict "context" . "component" "ui") | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "blackbeard.selectorLabels" (dict "context" . "component" "ui") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blackbeard.labels" . | nindent 8 }}
        {{- include "blackbeard.selectorLabels" (dict "context" . "component" "ui") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          image: {{ include "blackbeard.uiImage" . }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-cache
          emptyDir:
            sizeLimit: 50Mi
        - name: nginx-conf
          emptyDir:
            sizeLimit: 1Mi
        - name: nginx-run
          emptyDir:
            sizeLimit: 1Mi
