/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readiness
     * @description Readiness check -- verifies database, Valkey, and LiteLLM connectivity.
     *
     *     Returns 200 with status=healthy (all up) or status=degraded (non-critical
     *     component down). Returns 503 with status=unhealthy only when a critical
     *     component (database) is down.
     */
    get: operations['readiness_api_v1_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Register
     * @description Register a new user account.
     */
    post: operations['register_api_v1_auth_register_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Authenticate with email and password.
     */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh
     * @description Exchange a refresh token for a new access token.
     */
    post: operations['refresh_api_v1_auth_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Me
     * @description Get the currently authenticated user's profile.
     */
    get: operations['me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Users
     * @description List users with pagination (requires authentication).
     */
    get: operations['list_users_api_v1_users_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get User
     * @description Get a user by ID.
     */
    get: operations['get_user_api_v1_users__user_id__get']
    /**
     * Update User
     * @description Update a user (self-only — users can only modify their own profile).
     */
    put: operations['update_user_api_v1_users__user_id__put']
    post?: never
    /**
     * Deactivate User
     * @description Deactivate a user (self-only soft delete).
     */
    delete: operations['deactivate_user_api_v1_users__user_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Groups
     * @description List groups with pagination.
     */
    get: operations['list_groups_api_v1_groups_get']
    put?: never
    /**
     * Create Group
     * @description Create a new group.
     */
    post: operations['create_group_api_v1_groups_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups/{group_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Group
     * @description Get a group by ID.
     */
    get: operations['get_group_api_v1_groups__group_id__get']
    /**
     * Update Group
     * @description Update a group.
     */
    put: operations['update_group_api_v1_groups__group_id__put']
    post?: never
    /**
     * Delete Group
     * @description Delete a group. Idempotent.
     */
    delete: operations['delete_group_api_v1_groups__group_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/audit-logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Audit Logs
     * @description List audit log entries with optional filters. Requires authentication.
     */
    get: operations['list_audit_logs_api_v1_audit_logs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Chat
     * @description Send an ad-hoc chat completion through LiteLLM.
     */
    post: operations['chat_api_v1_chat_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Test Model
     * @description Test connectivity and API key validity for a specific model.
     *
     *     Sends a minimal prompt ("Say hi") and checks if the model responds.
     */
    post: operations['test_model_api_v1_models_test_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/available': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Available Models
     * @description List all models configured in the LiteLLM proxy.
     */
    get: operations['list_available_models_api_v1_models_available_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/crews/{crew_name}/kickoff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Kickoff Crew
     * @description Kick off a crew execution. Returns immediately with status=queued.
     */
    post: operations['kickoff_crew_api_v1_crews__crew_name__kickoff_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/crews/{crew_name}/train': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Train Crew Endpoint
     * @description Start a crew training run. Returns immediately with status=queued.
     */
    post: operations['train_crew_endpoint_api_v1_crews__crew_name__train_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/crews/{crew_name}/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Test Crew Endpoint
     * @description Start a crew test run. Returns immediately with status=queued.
     */
    post: operations['test_crew_endpoint_api_v1_crews__crew_name__test_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/flows/{flow_name}/run': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run Flow Endpoint
     * @description Run a flow. Returns immediately with status=queued.
     */
    post: operations['run_flow_endpoint_api_v1_flows__flow_name__run_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/executions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Executions
     * @description List executions with optional filters.
     */
    get: operations['list_executions_api_v1_executions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/executions/{execution_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Execution
     * @description Get execution details by ID.
     */
    get: operations['get_execution_api_v1_executions__execution_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/executions/{execution_id}/spend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Execution Spend
     * @description Get LiteLLM spend data for an execution's requests.
     */
    get: operations['get_execution_spend_api_v1_executions__execution_id__spend_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/executions/{execution_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Execution Events
     * @description List execution events, optionally after a given sequence number.
     */
    get: operations['list_execution_events_api_v1_executions__execution_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/executions/{execution_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Cancel Execution
     * @description Cancel a queued or running execution.
     */
    patch: operations['cancel_execution_api_v1_executions__execution_id__cancel_patch']
    trace?: never
  }
  '/api/v1/executions/{execution_id}/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream Execution
     * @description SSE stream of execution status events.
     */
    get: operations['stream_execution_api_v1_executions__execution_id__stream_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/{kind_plural}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Resources
     * @description List resources of a given kind.
     */
    get: operations['list_resources_api_v1__kind_plural__get']
    put?: never
    /**
     * Create Resource
     * @description Create (or upsert) a resource of a given kind.
     */
    post: operations['create_resource_api_v1__kind_plural__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/{kind_plural}/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Resource
     * @description Get a single resource by kind and name.
     */
    get: operations['get_resource_api_v1__kind_plural___name__get']
    /**
     * Update Resource
     * @description Update a resource by kind and name (optimistic locking via version).
     */
    put: operations['update_resource_api_v1__kind_plural___name__put']
    post?: never
    /**
     * Delete Resource
     * @description Delete a resource by kind and name. Idempotent.
     */
    delete: operations['delete_resource_api_v1__kind_plural___name__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AuditLogItem
     * @description Single audit log entry returned by the API.
     */
    AuditLogItem: {
      /** Id */
      id: string
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string
      /** Actor Type */
      actor_type: string
      /** Actor Id */
      actor_id: string
      /** Actor Email */
      actor_email?: string | null
      /** Action */
      action: string
      /** Resource Type */
      resource_type?: string | null
      /** Resource Id */
      resource_id?: string | null
      /** Detail */
      detail?: {
        [key: string]: unknown
      } | null
      /** Request Id */
      request_id?: string | null
      /** Ip Address */
      ip_address?: string | null
    }
    /**
     * AuditLogListResponse
     * @description Paginated list of audit log entries.
     */
    AuditLogListResponse: {
      /** Items */
      items: components['schemas']['AuditLogItem'][]
      /** Total */
      total: number
      /**
       * Limit
       * @default 100
       */
      limit: number
      /**
       * Offset
       * @default 0
       */
      offset: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * AuthResponse
     * @description Authentication response with tokens and user profile.
     */
    AuthResponse: {
      /** Access Token */
      access_token: string
      /** Refresh Token */
      refresh_token: string
      /**
       * Token Type
       * @default bearer
       */
      token_type: string
      user: components['schemas']['UserResponse']
    }
    /** Body_test_model_api_v1_models_test_post */
    Body_test_model_api_v1_models_test_post: {
      /** Model */
      model: string
    }
    /** ChatMessage */
    ChatMessage: {
      /**
       * Role
       * @default user
       * @enum {string}
       */
      role: 'system' | 'user' | 'assistant'
      /** Content */
      content: string
    }
    /** ChatRequest */
    ChatRequest: {
      /**
       * Model
       * @description Model name from LiteLLM config
       */
      model: string
      /** Messages */
      messages: components['schemas']['ChatMessage'][]
      /** Temperature */
      temperature?: number | null
      /** Max Tokens */
      max_tokens?: number | null
    }
    /** ChatResponse */
    ChatResponse: {
      /** Model */
      model: string
      /** Content */
      content: string
      tokens: components['schemas']['TokenUsage']
      /** Latency Ms */
      latency_ms: number
    }
    /** ComponentCheck */
    ComponentCheck: {
      /**
       * Status
       * @enum {string}
       */
      status: 'up' | 'down' | 'degraded' | 'saturated'
      /** Latency Ms */
      latency_ms?: number | null
      /** Reason */
      reason?: string | null
      /** Http Status */
      http_status?: number | null
      /** Active Threads */
      active_threads?: number | null
      /** Queued Tasks */
      queued_tasks?: number | null
      /** Max Workers */
      max_workers?: number | null
    }
    /**
     * ExecutionEventItem
     * @description Single event from an execution.
     */
    ExecutionEventItem: {
      /** Sequence */
      sequence: number
      /** Event Type */
      event_type: string
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string
      /** Data */
      data: {
        [key: string]: unknown
      }
    }
    /**
     * ExecutionEventsResponse
     * @description Response for listing execution events.
     */
    ExecutionEventsResponse: {
      /** Events */
      events: components['schemas']['ExecutionEventItem'][]
      /** Next Sequence */
      next_sequence: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * ExecutionListResponse
     * @description Paginated list of executions.
     */
    ExecutionListResponse: {
      /** Items */
      items: components['schemas']['ExecutionResponse'][]
      /** Total */
      total: number
      /**
       * Limit
       * @default 100
       */
      limit: number
      /**
       * Offset
       * @default 0
       */
      offset: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * ExecutionResponse
     * @description Response for an execution.
     */
    ExecutionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Crew Name */
      crew_name: string
      /** Crew Project */
      crew_project: string
      /**
       * Execution Type
       * @description Execution mode: kickoff, train, test, or flow
       * @default kickoff
       * @enum {string}
       */
      execution_type: 'kickoff' | 'train' | 'test' | 'flow'
      /**
       * Status
       * @description Execution status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled'
      /** N Iterations */
      n_iterations?: number | null
      /** Training File */
      training_file?: string | null
      /** Inputs */
      inputs: {
        [key: string]: unknown
      }
      /** Outputs */
      outputs?: {
        [key: string]: unknown
      } | null
      /** Error */
      error?: string | null
      /**
       * Total Tokens
       * @default 0
       */
      total_tokens: number
      /**
       * Prompt Tokens
       * @default 0
       */
      prompt_tokens: number
      /**
       * Completion Tokens
       * @default 0
       */
      completion_tokens: number
      /**
       * Cost Usd
       * @default 0
       */
      cost_usd: string
      /** Initiated By */
      initiated_by?: string | null
      /** Principal Chain */
      principal_chain?: {
        [key: string]: unknown
      } | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Started At */
      started_at?: string | null
      /** Completed At */
      completed_at?: string | null
      /** Tasks */
      tasks?: components['schemas']['ExecutionTaskResponse'][]
    }
    /**
     * ExecutionStatus
     * @description Execution lifecycle states.
     * @enum {string}
     */
    ExecutionStatus: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled'
    /**
     * ExecutionTaskResponse
     * @description Response for a single task within an execution.
     */
    ExecutionTaskResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Task Name */
      task_name: string
      /** Agent Name */
      agent_name?: string | null
      /** Order */
      order: number
      /**
       * Status
       * @description Task status
       * @enum {string}
       */
      status: 'pending' | 'running' | 'completed' | 'failed'
      /** Output */
      output?: string | null
      /** Error */
      error?: string | null
      /**
       * Tokens Used
       * @default 0
       */
      tokens_used: number
      /**
       * Cost Usd
       * @default 0
       */
      cost_usd: string
      /** Started At */
      started_at?: string | null
      /** Completed At */
      completed_at?: string | null
    }
    /**
     * GroupCreateRequest
     * @description Create a new group.
     */
    GroupCreateRequest: {
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * GroupListResponse
     * @description Paginated group list.
     */
    GroupListResponse: {
      /** Items */
      items: components['schemas']['GroupResponse'][]
      /** Total */
      total: number
      /**
       * Limit
       * @default 100
       */
      limit: number
      /**
       * Offset
       * @default 0
       */
      offset: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * GroupResponse
     * @description Group response.
     */
    GroupResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * GroupUpdateRequest
     * @description Update group fields.
     */
    GroupUpdateRequest: {
      /** Description */
      description?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Service */
      service: string
      /** Version */
      version: string
      /** Uptime S */
      uptime_s?: number | null
    }
    /**
     * KickoffRequest
     * @description Request to kick off a crew execution.
     */
    KickoffRequest: {
      /**
       * Inputs
       * @description Key-value inputs passed to the crew (max 100 entries)
       */
      inputs?: {
        [key: string]: unknown
      }
    }
    /**
     * LoginRequest
     * @description User login request.
     */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
    }
    /** ModelInfo */
    ModelInfo: {
      /** Name */
      name: string
      /** Provider */
      provider?: string | null
      /** Model Id */
      model_id?: string | null
    }
    /** ModelTestResult */
    ModelTestResult: {
      /** Model */
      model: string
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'error'
      /** Latency Ms */
      latency_ms?: number | null
      /** Error */
      error?: string | null
      /** Response Preview */
      response_preview?: string | null
      tokens?: components['schemas']['TokenUsage'] | null
      /** Context Length */
      context_length?: number | null
      /** Parameter Size */
      parameter_size?: string | null
    }
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'healthy' | 'degraded' | 'unhealthy'
      /** Service */
      service: string
      /** Version */
      version: string
      /** Uptime S */
      uptime_s?: number | null
      /** Checks */
      checks: {
        [key: string]: components['schemas']['ComponentCheck']
      }
    }
    /**
     * RefreshRequest
     * @description Token refresh request.
     */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string
    }
    /**
     * RegisterRequest
     * @description User registration request.
     */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
      /** Display Name */
      display_name: string
    }
    /**
     * ResourceCreate
     * @description Schema for creating a resource via API or YAML apply.
     */
    ResourceCreate: {
      /**
       * Apiversion
       * @default blackbeard/v1
       */
      apiVersion: string
      /** Kind */
      kind: string
      metadata: components['schemas']['ResourceMetadata']
      /** Spec */
      spec: {
        [key: string]: unknown
      }
    }
    /**
     * ResourceListResponse
     * @description Paginated list of resources.
     */
    ResourceListResponse: {
      /** Items */
      items: components['schemas']['ResourceResponse'][]
      /** Total */
      total: number
      /**
       * Limit
       * @default 100
       */
      limit: number
      /**
       * Offset
       * @default 0
       */
      offset: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * ResourceMetadata
     * @description Resource metadata block (mirrors YAML metadata section).
     */
    ResourceMetadata: {
      /** Name */
      name: string
      /**
       * Project
       * @default default
       */
      project: string
      /** Labels */
      labels?: {
        [key: string]: string
      }
    }
    /**
     * ResourceResponse
     * @description Schema for resource API responses.
     */
    ResourceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Apiversion
       * @default blackbeard/v1
       */
      apiVersion: string
      /** Kind */
      kind: string
      metadata: components['schemas']['ResourceMetadata']
      /** Spec */
      spec: {
        [key: string]: unknown
      }
      /** Version */
      version: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ResourceUpdate
     * @description Schema for updating a resource (partial or full).
     */
    ResourceUpdate: {
      metadata?: components['schemas']['ResourceMetadata'] | null
      /** Spec */
      spec?: {
        [key: string]: unknown
      } | null
      /**
       * Version
       * @description Current version for optimistic locking
       */
      version: number
    }
    /**
     * TestRequest
     * @description Request to test a crew.
     */
    TestRequest: {
      /**
       * Inputs
       * @description Key-value inputs passed to the crew (max 100 entries)
       */
      inputs?: {
        [key: string]: unknown
      }
      /**
       * N Iterations
       * @description Number of test iterations
       * @default 3
       */
      n_iterations: number
    }
    /**
     * TokenResponse
     * @description Token refresh response.
     */
    TokenResponse: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       */
      token_type: string
    }
    /** TokenUsage */
    TokenUsage: {
      /**
       * Prompt
       * @default 0
       */
      prompt: number
      /**
       * Completion
       * @default 0
       */
      completion: number
      /**
       * Total
       * @default 0
       */
      total: number
    }
    /**
     * TrainRequest
     * @description Request to train a crew.
     */
    TrainRequest: {
      /**
       * Inputs
       * @description Key-value inputs passed to the crew (max 100 entries)
       */
      inputs?: {
        [key: string]: unknown
      }
      /**
       * N Iterations
       * @description Number of training iterations
       * @default 3
       */
      n_iterations: number
      /**
       * Filename
       * @description Filename for training data output
       * @default training_data.pkl
       */
      filename: string
    }
    /**
     * UserListResponse
     * @description Paginated user list.
     */
    UserListResponse: {
      /** Items */
      items: components['schemas']['UserResponse'][]
      /** Total */
      total: number
      /**
       * Limit
       * @default 100
       */
      limit: number
      /**
       * Offset
       * @default 0
       */
      offset: number
      /**
       * Has More
       * @default false
       */
      has_more: boolean
    }
    /**
     * UserResponse
     * @description Public user profile.
     */
    UserResponse: {
      /** Id */
      id: string
      /** Email */
      email: string
      /** Display Name */
      display_name: string
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Last Login At */
      last_login_at?: string | null
    }
    /**
     * UserUpdateRequest
     * @description Update fields on the authenticated user's own profile.
     */
    UserUpdateRequest: {
      /** Display Name */
      display_name?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  readiness_api_v1_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
      /** @description Critical component (database) is down */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
    }
  }
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid email or password */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Account is deactivated */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Refresh token expired, invalid, or user inactive */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Missing or invalid Bearer token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        /** @description Max results */
        limit?: number
        /** @description Results to skip */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserListResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_api_v1_users__user_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Cannot modify other users */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deactivate_user_api_v1_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Cannot deactivate other users */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_groups_api_v1_groups_get: {
    parameters: {
      query?: {
        /** @description Max results */
        limit?: number
        /** @description Results to skip */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupListResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_group_api_v1_groups_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Group name already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_group_api_v1_groups__group_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_group_api_v1_groups__group_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_group_api_v1_groups__group_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group deleted (or did not exist — idempotent) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_audit_logs_api_v1_audit_logs_get: {
    parameters: {
      query?: {
        /** @description Filter by action (e.g. 'user_login', 'resource_created') */
        action?: string | null
        /** @description Filter by actor ID (user UUID or 'api_key') */
        actor_id?: string | null
        /** @description Filter by resource type (e.g. 'Agent', 'Crew') */
        resource_type?: string | null
        /** @description Filter by resource ID (resource name or UUID) */
        resource_id?: string | null
        /** @description Max results */
        limit?: number
        /** @description Results to skip */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditLogListResponse']
        }
      }
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  chat_api_v1_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChatResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Model rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description LiteLLM proxy unreachable or model error */
      502: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  test_model_api_v1_models_test_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Body_test_model_api_v1_models_test_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelTestResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description LiteLLM proxy unreachable or model error */
      502: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_available_models_api_v1_models_available_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInfo'][]
        }
      }
      /** @description Model proxy rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description LiteLLM proxy unreachable */
      502: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  kickoff_crew_api_v1_crews__crew_name__kickoff_post: {
    parameters: {
      query?: {
        /** @description Namespace containing the crew */
        project?: string
      }
      header?: never
      path: {
        /** @description Name of the crew to execute */
        crew_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['KickoffRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Crew not found in project */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal execution error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  train_crew_endpoint_api_v1_crews__crew_name__train_post: {
    parameters: {
      query?: {
        /** @description Namespace containing the crew */
        project?: string
      }
      header?: never
      path: {
        /** @description Name of the crew to train */
        crew_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TrainRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Crew not found in project */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal execution error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  test_crew_endpoint_api_v1_crews__crew_name__test_post: {
    parameters: {
      query?: {
        /** @description Namespace containing the crew */
        project?: string
      }
      header?: never
      path: {
        /** @description Name of the crew to test */
        crew_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TestRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Crew not found in project */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal execution error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  run_flow_endpoint_api_v1_flows__flow_name__run_post: {
    parameters: {
      query?: {
        /** @description Namespace containing the flow */
        project?: string
      }
      header?: never
      path: {
        /** @description Name of the flow to run */
        flow_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['KickoffRequest']
      }
    }
    responses: {
      /** @description Flow execution queued */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Flow not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_executions_api_v1_executions_get: {
    parameters: {
      query?: {
        /** @description Filter by crew name */
        crew_name?: string | null
        /** @description Filter by project (omit for all projects) */
        project?: string | null
        /** @description Filter by execution status */
        status?: components['schemas']['ExecutionStatus'] | null
        /** @description Max results */
        limit?: number
        /** @description Results to skip */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of executions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_execution_api_v1_executions__execution_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution UUID */
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_execution_spend_api_v1_executions__execution_id__spend_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution UUID */
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description LiteLLM spend data for this execution */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description LiteLLM spend service unavailable */
      502: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_execution_events_api_v1_executions__execution_id__events_get: {
    parameters: {
      query?: {
        /** @description Return events with sequence > after */
        after?: number
        /** @description Max events to return */
        limit?: number
      }
      header?: never
      path: {
        /** @description Execution UUID */
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of execution events for streaming/replay */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionEventsResponse']
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_execution_api_v1_executions__execution_id__cancel_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution UUID */
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Execution cancelled successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExecutionResponse']
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Execution already in terminal status */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stream_execution_api_v1_executions__execution_id__stream_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution UUID */
        execution_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description SSE stream of execution status and heartbeat events */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Too many concurrent SSE streams */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_resources_api_v1__kind_plural__get: {
    parameters: {
      query?: {
        /** @description Filter by project (omit for all projects) */
        project?: string | null
        /** @description Comma-separated label filters, e.g. 'env=prod,team=ml' */
        label_selector?: string | null
        /** @description Max results */
        limit?: number
        /** @description Results to skip */
        offset?: number
      }
      header?: never
      path: {
        kind_plural: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceListResponse']
        }
      }
      /** @description Invalid label_selector format */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unknown resource kind */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_resource_api_v1__kind_plural__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind_plural: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResourceCreate']
      }
    }
    responses: {
      /** @description Resource updated (upsert) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceResponse']
        }
      }
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceResponse']
        }
      }
      /** @description Validation error or kind mismatch between URL and body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_resource_api_v1__kind_plural___name__get: {
    parameters: {
      query?: {
        /** @description Resource project */
        project?: string
      }
      header?: never
      path: {
        kind_plural: string
        /** @description Resource name */
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceResponse']
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_resource_api_v1__kind_plural___name__put: {
    parameters: {
      query?: {
        /** @description Resource project */
        project?: string
      }
      header?: never
      path: {
        kind_plural: string
        /** @description Resource name */
        name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResourceUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourceResponse']
        }
      }
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Version conflict (optimistic locking) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error or name/project mismatch */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_resource_api_v1__kind_plural___name__delete: {
    parameters: {
      query?: {
        /** @description Resource project */
        project?: string
      }
      header?: never
      path: {
        kind_plural: string
        /** @description Resource name */
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Resource deleted (or did not exist — idempotent) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
