# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from blackbeard.grpc import blackbeard_pb2 as blackbeard__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in blackbeard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlackbeardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListResources = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/ListResources',
                request_serializer=blackbeard__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/GetResource',
                request_serializer=blackbeard__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.Resource.FromString,
                _registered_method=True)
        self.CreateResource = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/CreateResource',
                request_serializer=blackbeard__pb2.CreateResourceRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.Resource.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/DeleteResource',
                request_serializer=blackbeard__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Kickoff = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/Kickoff',
                request_serializer=blackbeard__pb2.KickoffRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.Execution.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/GetExecution',
                request_serializer=blackbeard__pb2.GetExecutionRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.Execution.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/blackbeard.v1.BlackbeardService/StreamEvents',
                request_serializer=blackbeard__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.ExecutionEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/blackbeard.v1.BlackbeardService/Health',
                request_serializer=blackbeard__pb2.HealthRequest.SerializeToString,
                response_deserializer=blackbeard__pb2.HealthResponse.FromString,
                _registered_method=True)


class BlackbeardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kickoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlackbeardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=blackbeard__pb2.ListResourcesRequest.FromString,
                    response_serializer=blackbeard__pb2.ListResourcesResponse.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=blackbeard__pb2.GetResourceRequest.FromString,
                    response_serializer=blackbeard__pb2.Resource.SerializeToString,
            ),
            'CreateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResource,
                    request_deserializer=blackbeard__pb2.CreateResourceRequest.FromString,
                    response_serializer=blackbeard__pb2.Resource.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=blackbeard__pb2.DeleteResourceRequest.FromString,
                    response_serializer=blackbeard__pb2.DeleteResponse.SerializeToString,
            ),
            'Kickoff': grpc.unary_unary_rpc_method_handler(
                    servicer.Kickoff,
                    request_deserializer=blackbeard__pb2.KickoffRequest.FromString,
                    response_serializer=blackbeard__pb2.Execution.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=blackbeard__pb2.GetExecutionRequest.FromString,
                    response_serializer=blackbeard__pb2.Execution.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=blackbeard__pb2.StreamEventsRequest.FromString,
                    response_serializer=blackbeard__pb2.ExecutionEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=blackbeard__pb2.HealthRequest.FromString,
                    response_serializer=blackbeard__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blackbeard.v1.BlackbeardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blackbeard.v1.BlackbeardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlackbeardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/ListResources',
            blackbeard__pb2.ListResourcesRequest.SerializeToString,
            blackbeard__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/GetResource',
            blackbeard__pb2.GetResourceRequest.SerializeToString,
            blackbeard__pb2.Resource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/CreateResource',
            blackbeard__pb2.CreateResourceRequest.SerializeToString,
            blackbeard__pb2.Resource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/DeleteResource',
            blackbeard__pb2.DeleteResourceRequest.SerializeToString,
            blackbeard__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kickoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/Kickoff',
            blackbeard__pb2.KickoffRequest.SerializeToString,
            blackbeard__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/GetExecution',
            blackbeard__pb2.GetExecutionRequest.SerializeToString,
            blackbeard__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/StreamEvents',
            blackbeard__pb2.StreamEventsRequest.SerializeToString,
            blackbeard__pb2.ExecutionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackbeard.v1.BlackbeardService/Health',
            blackbeard__pb2.HealthRequest.SerializeToString,
            blackbeard__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
